/** 2.0.0 (#161, #162): print a check from a register transaction (Register Users).
 *
 * The amounts are generated by the server from the transaction total; nothing here can change them. Before every
 * print and reprint the user confirms the number printed on the check loaded in the printer (the app never prints the
 * check number). After printing: done, reprint (check not damaged) or mark spoiled (the number becomes a zero-dollar
 * VOID record and the payment moves to the next number). */
import { useEffect, useMemo, useState, type FormEvent } from "react";
import { api, money } from "../api";
import { ErrorBox, Field, GuardedForm, Loading, Modal } from "../components";
import { EnclosuresPanel, HandwrittenPanel } from "./CheckEnclosures";
import { BrowserTips, CheckPreview, FIELD_LABELS, PatternInput, PdfViewer, useCheckFonts, usePdf } from "./checkShared";

type Opts = any;

export function PrintCheckDialog({ txn, onClose, onChanged }: { txn: any; onClose: () => void; onChanged: () => void }) {
  const [o, setO] = useState<Opts | null>(null);
  const [err, setErr] = useState<unknown>(null);
  const load = () => api.get(`/api/checks/transactions/${txn.id}/options`).then(setO, setErr);
  useEffect(() => { load(); }, [txn.id]); // eslint-disable-line react-hooks/exhaustive-deps
  const [mode, setMode] = useState<"print" | "hand">("print");
  const defaultSigner = o ? (o.signers.find((s: any) => s.id === o.default_signer_id) || o.signers[0])?.id ?? null : null;
  return (
    <Modal title={`Print check – transaction #${txn.id}`} onClose={onClose} wide>
      <ErrorBox error={err} />
      {o && o.has_documents ? (
        <div className="segmented" role="radiogroup" aria-label="How is the check made">
          <label><input type="radio" name="mode" checked={mode === "print"} onChange={() => setMode("print")} /> Print the check</label>
          <label><input type="radio" name="mode" checked={mode === "hand"} onChange={() => setMode("hand")} /> I'm writing the check by hand</label>
        </div>
      ) : null}
      {o && mode === "hand" ? (
        <HandwrittenPanel txn={o.transaction} nextNumber={o.next_check_number} signerId={defaultSigner} onChanged={() => { onChanged(); load(); }} />
      ) : !o ? (err ? null : <Loading />) : !o.check_style_id ? (
        <ChooseStyle o={o} onDone={load} />
      ) : (
        <PrintForm o={o} reload={load} onClose={onClose} onChanged={onChanged} />
      )}
    </Modal>
  );
}

function ChooseStyle({ o, onDone }: { o: Opts; onDone: () => void }) {
  const [style, setStyle] = useState(o.styles[0]?.id ? String(o.styles[0].id) : "");
  const [left, setLeft] = useState("");
  const [err, setErr] = useState<unknown>(null);
  const chosen = o.styles.find((s: any) => String(s.id) === style);
  const go = async (e: FormEvent) => {
    e.preventDefault();
    try { await api.put(`/api/checks/accounts/${o.transaction.bank_account_id}`, { check_style_id: Number(style), sheet_remaining: left ? Number(left) : null }); onDone(); } catch (x) { setErr(x); }
  };
  if (!o.styles.length) return <div className="alert warn">No check styles are set up yet. Ask an Administrator to set up Check Printing.</div>;
  return (
    <GuardedForm onSubmit={go}>
      <ErrorBox error={err} />
      <p>Which check stock is used for <b>{o.transaction.bank_account_name}</b>? This is remembered for the account and can be changed later.</p>
      <Field label="Check style"><select value={style} onChange={(e) => setStyle(e.target.value)}>{o.styles.map((s: any) => <option key={s.id} value={s.id}>{s.name}</option>)}</select></Field>
      {chosen && chosen.checks_per_sheet > 1 ? (
        <Field label="Checks left on the sheet in the printer">
          <select value={left} onChange={(e) => setLeft(e.target.value)}>
            <option value="">A full sheet ({chosen.checks_per_sheet})</option>
            {Array.from({ length: chosen.checks_per_sheet - 1 }, (_, i) => chosen.checks_per_sheet - 1 - i).map((n) => <option key={n} value={n}>{n}</option>)}
          </select>
        </Field>
      ) : null}
      <div className="actions"><button className="primary" type="submit" disabled={!style}>Continue</button></div>
    </GuardedForm>
  );
}

function PrintForm({ o, reload, onClose, onChanged }: { o: Opts; reload: () => void; onClose: () => void; onChanged: () => void }) {
  const cfg = o.style_config;
  const t = o.transaction;
  useCheckFonts(o.fonts);
  const [feed, setFeed] = useState<string>(o.suggested_feed);
  useEffect(() => { setFeed(o.suggested_feed); }, [o.suggested_feed]);
  const signerDefault = o.signers.some((s: any) => s.id === o.default_signer_id) ? String(o.default_signer_id) : o.signers[0] ? String(o.signers[0].id) : "";
  const [signer, setSigner] = useState(signerDefault);
  const [memoPattern, setMemoPattern] = useState<string>(o.memo_default || "");
  const [overrides, setOverrides] = useState<{ payee_text?: string; memo_text?: string }>({});
  const [editing, setEditing] = useState<string | null>(null);
  const [confirmed, setConfirmed] = useState<Set<string>>(new Set());
  const [prep, setPrep] = useState<any>(null);
  const [prepErr, setPrepErr] = useState<unknown>(null);
  const [checkNo, setCheckNo] = useState<string>(t.check_number || o.next_check_number || "");
  const [typed, setTyped] = useState("");
  const [reason, setReason] = useState("");
  const [err, setErr] = useState<unknown>(null);
  const [busy, setBusy] = useState(false);
  const [pdf, setPdf] = usePdf();
  const [align, setAlign] = usePdf();
  const [viewing, setViewing] = useState<null | "check" | "align">(null);   // #174: PDFs open in the page
  const [printed, setPrinted] = useState(false);
  const [spoiling, setSpoiling] = useState(false);
  const [assistant, setAssistant] = useState(false);
  const [counter, setCounter] = useState(false);
  const feedMode = cfg.feed_modes.find((m: any) => m.key === feed);
  const printer = o.printer.find((p: any) => p.feed_key === feed);
  const body = useMemo(() => ({
    check_style_id: o.check_style_id, feed_key: feed, memo_pattern: memoPattern,
    signer_id: signer ? Number(signer) : null, no_signature: !signer, ...overrides,
  }), [o.check_style_id, feed, memoPattern, signer, overrides]);
  useEffect(() => {
    const h = setTimeout(() => {
      // a pattern being typed (e.g. "{B") is refused until it is valid: keep the last preview, block printing
      api.post(`/api/checks/transactions/${t.id}/prepare`, body).then((p) => { setPrep(p); setPrepErr(null); }, (x) => setPrepErr(x));
    }, 200);
    return () => clearTimeout(h);
  }, [body, t.id]);
  const warnings: any[] = prep?.warnings || [];
  const allConfirmed = warnings.every((w) => confirmed.has(w.code));
  const number = t.check_number || checkNo.trim();
  const reprint = !!o.is_reprint;
  const canPrint = prep?.can_print && !prepErr && allConfirmed && !!number && typed.trim() === number && (!reprint || reason.trim()) && !busy;
  const doPrint = async () => {
    setErr(null); setBusy(true);
    try {
      const blob = await api.postBlob(`/api/checks/transactions/${t.id}/print`, {
        ...body, check_number: t.check_number ? null : number, confirm_check_number: typed.trim(),
        reprint_reason: reprint ? reason : null, confirmations: [...confirmed],
      });
      setPdf(blob, `check-${number}.pdf`);
      setPrinted(true);
      setViewing("check");
      onChanged();
    } catch (x) { setErr(x); } finally { setBusy(false); }
  };
  const alignment = async () => {
    setErr(null);
    try { setAlign(await api.postBlob(`/api/checks/transactions/${t.id}/alignment-test`, body), "alignment-test.pdf"); setViewing("align"); } catch (x) { setErr(x); }
  };
  const afterPrint = (what: "done" | "reprint" | "spoil") => {
    if (what === "done") { onClose(); return; }
    if (what === "spoil") { setSpoiling(true); return; }
    setPrinted(false); setTyped(""); setReason(""); setPdf(null); reload();
  };
  const texts = prep?.fields || null;
  const problems = texts ? Object.entries(texts).filter(([, f]: any) => !f.fits) : [];
  const setOverride = (field: string, v: string | undefined) => {
    const k = field === "payee" ? "payee_text" : "memo_text";
    setOverrides((cur) => { const n: any = { ...cur }; if (v === undefined) delete n[k]; else n[k] = v; return n; });
  };

  if (printed) {
    return (
      <div className="print-check">
        <div className="alert success" role="status"><strong>Check #{number} is ready.</strong> Print it at actual size (100%).</div>
        <div className="actions left"><button onClick={() => setViewing("check")}>Show the check again</button></div>
        {pdf && viewing === "check" ? (
          <PdfViewer pdf={pdf} title={`Check #${number}`} singleFeed={feedMode?.kind === "SINGLE"} onClose={() => setViewing(null)}>
            <p className="hint">Load check <b>#{number}</b>{feedMode?.kind === "SINGLE" ? " in the manual feed" : ""}, then <b>Print…</b>. Close this window afterwards to say whether it printed correctly.</p>
          </PdfViewer>
        ) : null}
        <h3>Did the check print correctly?</h3>
        <div className="actions left">
          <button className="primary" onClick={() => afterPrint("done")}>Yes – done</button>
          <button onClick={() => afterPrint("reprint")}>Reprint (the check was not damaged)</button>
          <button className="danger" onClick={() => afterPrint("spoil")}>Mark spoiled… (damaged, or printed in the wrong place)</button>
        </div>
        <p className="hint">A misaligned print counts as spoiled: the check has ink on it. Reprint only when the check came out blank or undamaged and you
          put the same check back in the printer.</p>
        <EnclosuresPanel txnId={t.id} signerId={signer ? Number(signer) : null} onChanged={onChanged}
          intro="Optional. The letter is signed by name by the check's signer. Printed letters and envelopes are attached to the transaction." />
        {spoiling ? <SpoilDialog txn={t} number={number} next={o.next_check_number} onClose={() => setSpoiling(false)} onDone={() => { setSpoiling(false); setPrinted(false); setTyped(""); setPdf(null); onChanged(); reload(); }} /> : null}
      </div>
    );
  }
  return (
    <div className="print-check">
      <ErrorBox error={err} />
      <dl className="dl">
        <dt>Pay to</dt><dd>{t.payee || <span className="badge red">No payee</span>}</dd>
        <dt>Amount</dt><dd>{money(t.amount)}</dd>
        <dt>Date</dt><dd>{t.transaction_date}</dd>
        <dt>Bank account</dt><dd>{t.bank_account_name} · {o.styles.find((s: any) => s.id === o.check_style_id)?.name}</dd>
      </dl>
      {reprint ? (
        <div className="alert warn" role="alert">
          <strong>Check #{t.check_number} was already printed</strong>{o.print_status ? ` (${o.print_status.printed_at.slice(0, 10)} by ${o.print_status.printed_by})` : ""}.
          Reprint only on the same, undamaged check. If it was damaged, mark it spoiled instead.
          <Field label="Reason for the reprint (required)"><input maxLength={500} value={reason} onChange={(e) => setReason(e.target.value)} placeholder="e.g. printer jam, check undamaged" /></Field>
        </div>
      ) : null}
      <div className="row">
        <Field label="Feed mode" hint={feedMode?.note || undefined}>
          <select value={feed} onChange={(e) => setFeed(e.target.value)}>
            {cfg.feed_modes.map((m: any) => <option key={m.key} value={m.key}>{m.label}{m.key === o.suggested_feed ? " (suggested)" : ""}</option>)}
          </select>
        </Field>
        {o.checks_per_sheet > 1 ? (
          <div className="field">
            <span className="label">Checks left on the sheet</span>
            <span>{o.sheet_remaining} of {o.checks_per_sheet} <button type="button" className="link small" onClick={() => setCounter(true)}>Change</button></span>
          </div>
        ) : null}
        <Field label="Signature" hint={prep?.signature_notice || undefined}>
          <select value={signer} onChange={(e) => setSigner(e.target.value)}>
            {o.signers.map((s: any) => <option key={s.id} value={s.id}>{s.name}{s.title ? ` (${s.title})` : ""}</option>)}
            <option value="">Print without signature</option>
          </select>
        </Field>
      </div>
      {feedMode?.kind === "SINGLE" ? <div className="alert info">Feed this check through the manual feed on its own{feedMode.lead === "DATE_END" ? ", date end first" : ", pay-to end first"}. {feedMode.note || ""}</div> : null}
      <PatternInput id="memo" label="Memo" value={memoPattern} variables={o.variables} onChange={(v) => { setMemoPattern(v); setOverride("memo", undefined); }} />
      <ErrorBox error={prepErr} />
      {prep ? (
        <>
          <CheckPreview cfg={cfg} fonts={o.fonts} texts={texts} showBoxes={false} signature={prep.signature} />
          {prep.signature_notice ? <div className="alert warn">{prep.signature_notice}</div> : null}
          {problems.map(([name, f]: any) => (
            <div key={name} className="alert warn fit-warning" role="alert" data-testid={`fit-${name}`}>
              <strong>{FIELD_LABELS[name]} does not fit on the check.</strong>
              <div>Full text: <code>{f.text}</code></div>
              {f.editable ? (
                <>
                  {f.suggestion ? <div>Shortened to fit: <code>{f.suggestion}</code></div> : null}
                  {editing === name ? (
                    <EditText initial={f.suggestion || f.text} onSave={(v) => { setOverride(name, v); setEditing(null); }} onCancel={() => setEditing(null)} label={`Edit the ${FIELD_LABELS[name].toLowerCase()}`} />
                  ) : (
                    <div className="actions left">
                      {f.suggestion ? <button className="primary small" onClick={() => setOverride(name, f.suggestion)}>Use the shortened text</button> : null}
                      <button className="small" onClick={() => setEditing(name)}>Edit it myself</button>
                    </div>
                  )}
                </>
              ) : <div>This can't be changed, so the check can't be printed with this layout. Ask an Administrator to adjust the check style.</div>}
            </div>
          ))}
          {overrides.payee_text || overrides.memo_text ? (
            <p className="hint">Using your changed {[overrides.payee_text ? "payee" : "", overrides.memo_text ? "memo" : ""].filter(Boolean).join(" and ")} text for this print only.{" "}
              <button className="link small" onClick={() => setOverrides({})}>Undo</button></p>
          ) : null}
          {warnings.map((w) => (
            <label key={w.code} className="check alert warn">
              <input type="checkbox" checked={confirmed.has(w.code)} onChange={(e) => { const n = new Set(confirmed); e.target.checked ? n.add(w.code) : n.delete(w.code); setConfirmed(n); }} /> {w.message}
            </label>
          ))}
        </>
      ) : !prepErr ? <Loading /> : null}
      <section className="card subtle">
        <h3>Check alignment on plain paper first (optional)</h3>
        <div className="row">
          <button type="button" onClick={alignment} disabled={!prep || !!prepErr}>Test print on plain paper</button>
          {align && viewing !== "align" ? <button className="link" onClick={() => setViewing("align")}>Show the test page again</button> : null}
          <button type="button" onClick={() => setAssistant(true)}>Printer setup assistant…</button>
        </div>
        <p className="hint">Hold the test page over a blank check against a light. It never uses a check and is not recorded as printed.
          {printer?.customized ? ` Your printer settings for this feed mode are applied (${adjText(printer)}).` : ""}
          {feedMode?.kind === "SINGLE" ? " For a single check, cut plain paper to the check's size or use a scrap check." : ""}</p>
      </section>
      <section className="card">
        <h3>Load the check</h3>
        {t.check_number ? (
          <p>Load check <b>#{t.check_number}</b> in the printer{feedMode?.kind === "SINGLE" ? " (manual feed)" : ""}.</p>
        ) : (
          <Field label="Check number of the check you are loading" hint={o.next_check_number ? `The next unused number in this account is ${o.next_check_number}.` : undefined}>
            <input maxLength={20} value={checkNo} onChange={(e) => setCheckNo(e.target.value)} />
          </Field>
        )}
        <Field label="Type the number printed on the check that is in the printer" hint="The app doesn't print the check number, so this keeps the register and the bank in agreement.">
          <input maxLength={20} value={typed} onChange={(e) => setTyped(e.target.value)} aria-invalid={!!typed && typed.trim() !== number} />
        </Field>
        {typed && typed.trim() !== number ? <p className="error-text" role="alert">That doesn't match check #{number}.</p> : null}
        <BrowserTips singleFeed={feedMode?.kind === "SINGLE"} />
        <div className="actions">
          {t.check_number ? <button type="button" className="danger" onClick={() => setSpoiling(true)}>Mark check #{t.check_number} spoiled…</button> : null}
          <button type="button" onClick={onClose}>Cancel</button>
          <button className="primary" disabled={!canPrint} onClick={doPrint}>{reprint ? "Reprint check" : "Print check"}</button>
        </div>
      </section>
      {align && viewing === "align" ? <PdfViewer pdf={align} title="Alignment test (plain paper)" singleFeed={feedMode?.kind === "SINGLE"} onClose={() => setViewing(null)} /> : null}
      {spoiling ? <SpoilDialog txn={t} number={t.check_number} next={o.next_check_number} onClose={() => setSpoiling(false)} onDone={() => { setSpoiling(false); setTyped(""); onChanged(); reload(); }} /> : null}
      {assistant ? <PrinterAssistant o={o} feed={feed} body={body} txnId={t.id} onClose={() => { setAssistant(false); reload(); }} /> : null}
      {counter ? <SheetCounter o={o} onClose={() => setCounter(false)} onDone={() => { setCounter(false); reload(); }} /> : null}
    </div>
  );
}

function adjText(p: any) {
  const parts = [];
  if (p.dx) parts.push(`${Math.abs(p.dx)}" ${p.dx > 0 ? "right" : "left"}`);
  if (p.dy) parts.push(`${Math.abs(p.dy)}" ${p.dy > 0 ? "down" : "up"}`);
  if (p.page) parts.push(p.page === "CHECK" ? "check-sized page" : `Letter page, ${String(p.guide || "center").toLowerCase()}`);
  return parts.join(", ") || "no adjustment";
}

function EditText({ initial, onSave, onCancel, label }: { initial: string; onSave: (v: string) => void; onCancel: () => void; label: string }) {
  const [v, setV] = useState(initial);
  return (
    <div className="row">
      <Field label={label}><input maxLength={200} value={v} onChange={(e) => setV(e.target.value)} autoFocus /></Field>
      <button className="primary small" onClick={() => onSave(v)} disabled={!v.trim()}>Use this text</button>
      <button className="small" onClick={onCancel}>Cancel</button>
    </div>
  );
}

function SheetCounter({ o, onClose, onDone }: { o: Opts; onClose: () => void; onDone: () => void }) {
  const [n, setN] = useState(String(o.sheet_remaining));
  const [err, setErr] = useState<unknown>(null);
  const go = async (e: FormEvent) => {
    e.preventDefault();
    try { await api.put(`/api/checks/accounts/${o.transaction.bank_account_id}`, { check_style_id: o.check_style_id, sheet_remaining: Number(n) }); onDone(); } catch (x) { setErr(x); }
  };
  return (
    <Modal title="Checks left on the sheet" onClose={onClose}>
      <GuardedForm onSubmit={go}>
        <ErrorBox error={err} />
        <p className="hint">How many checks are left on the sheet in the printer. It counts down by itself after each print; correct it after a tear or
          when you load a new sheet.</p>
        <Field label="Checks left"><select value={n} onChange={(e) => setN(e.target.value)}>{Array.from({ length: o.checks_per_sheet }, (_, i) => o.checks_per_sheet - i).map((x) => <option key={x} value={x}>{x}</option>)}</select></Field>
        <div className="actions"><button type="button" onClick={onClose}>Cancel</button><button className="primary" type="submit">Save</button></div>
      </GuardedForm>
    </Modal>
  );
}

const SPOIL_REASONS = ["Misaligned print", "Torn or jammed in the printer", "Printed on the wrong check", "Other"];

function SpoilDialog({ txn, number, next, onClose, onDone }: { txn: any; number: string; next: string | null; onClose: () => void; onDone: () => void }) {
  const [kind, setKind] = useState(SPOIL_REASONS[0]);
  const [detail, setDetail] = useState("");
  const [newNo, setNewNo] = useState(next || "");
  const [err, setErr] = useState<unknown>(null);
  const reason = kind === "Other" ? detail.trim() : detail.trim() ? `${kind}: ${detail.trim()}` : kind;
  const go = async (e: FormEvent) => {
    e.preventDefault();
    try { await api.post(`/api/checks/transactions/${txn.id}/spoil`, { reason, new_check_number: newNo.trim() }); onDone(); } catch (x) { setErr(x); }
  };
  return (
    <Modal title={`Mark check #${number} spoiled`} onClose={onClose}>
      <GuardedForm onSubmit={go}>
        <ErrorBox error={err} />
        <p>Check #{number} is recorded as a <b>$0.00 VOID record</b> in this account so the number is never used again, and this payment moves to
          the next check. Keep the spoiled check (write VOID on it) for your records.</p>
        <Field label="What happened"><select value={kind} onChange={(e) => setKind(e.target.value)}>{SPOIL_REASONS.map((r) => <option key={r}>{r}</option>)}</select></Field>
        <Field label={kind === "Other" ? "Reason (required)" : "Details (optional)"}><input maxLength={300} value={detail} onChange={(e) => setDetail(e.target.value)} required={kind === "Other"} /></Field>
        <Field label="Number of the next check (the one you will print on)"><input required maxLength={20} value={newNo} onChange={(e) => setNewNo(e.target.value)} /></Field>
        <div className="actions"><button type="button" onClick={onClose}>Cancel</button><button className="primary danger" type="submit" disabled={!reason || !newNo.trim()}>Mark spoiled</button></div>
      </GuardedForm>
    </Modal>
  );
}

// ------------------------------------------------------------------ printer setup assistant (#162)
const STEPS = [1 / 16, 1 / 8, 3 / 16, 1 / 4];

function PrinterAssistant({ o, feed, body, txnId, onClose }: { o: Opts; feed: string; body: any; txnId: number; onClose: () => void }) {
  const cfg = o.style_config;
  const fm = cfg.feed_modes.find((m: any) => m.key === feed);
  const single = fm?.kind === "SINGLE";
  const init = o.printer.find((p: any) => p.feed_key === feed) || { dx: 0, dy: 0, page: fm?.page, guide: fm?.guide };
  const [st, setSt] = useState<{ dx: number; dy: number; page: string | null; guide: string | null }>({ dx: init.dx, dy: init.dy, page: init.page, guide: init.guide });
  const [step, setStep] = useState<"scale" | "scale-bad" | "align" | "result" | "done">("scale");
  const [scalePdf, setScalePdf] = usePdf();
  const [testPdf, setTestPdf] = usePdf();
  const [show, setShow] = useState<null | "scale" | "test">(null);
  const [err, setErr] = useState<unknown>(null);
  const [outcome, setOutcome] = useState("");
  const [dir, setDir] = useState("down");
  const [amt, setAmt] = useState(String(STEPS[1]));
  const [note, setNote] = useState<string | null>(null);
  const save = async (next: typeof st) => {
    setSt(next);
    await api.put("/api/checks/my-printer", { check_style_id: o.check_style_id, feed_key: feed, page: single ? next.page : null, guide: single ? next.guide : null, dx: next.dx, dy: next.dy });
  };
  const printScale = async () => { setErr(null); try { const r = await fetch("/api/checks/scale-check", { credentials: "same-origin" }); setScalePdf(await r.blob(), "scale-check.pdf"); setShow("scale"); } catch (x) { setErr(x); } };
  const printTest = async () => { setErr(null); try { setTestPdf(await api.postBlob(`/api/checks/transactions/${txnId}/alignment-test`, body), "alignment-test.pdf"); setStep("result"); setShow("test"); } catch (x) { setErr(x); } };
  const apply = async () => {
    setErr(null);
    const a = Number(amt);
    const clamp = (v: number) => Math.max(-0.25, Math.min(0.25, Math.round(v * 1000) / 1000));
    let next = { ...st };
    let msg = "";
    try {
      if (outcome === "shifted") {
        // the printing landed too far <dir>: move it the other way
        if (dir === "down") next.dy = clamp(st.dy - a); else if (dir === "up") next.dy = clamp(st.dy + a);
        else if (dir === "right") next.dx = clamp(st.dx - a); else next.dx = clamp(st.dx + a);
        msg = Math.abs(next.dx) >= 0.25 || Math.abs(next.dy) >= 0.25
          ? "Your adjustment is at the 1/4 inch limit. If it's still off, ask an Administrator to adjust the feed mode's offset."
          : "Adjusted. Print the test page again.";
      } else if (outcome === "papersize" && single) {
        next.page = st.page === "CHECK" ? "LETTER" : "CHECK";
        msg = next.page === "CHECK" ? "Switched to a check-sized page. Print the test again." : "Switched to a Letter page with the check placed at the guides. Print the test again.";
      } else if (outcome === "wrongplace" && single) {
        next.page = "LETTER";
        next.guide = st.guide === "CENTER" ? "LEFT" : st.guide === "LEFT" ? "RIGHT" : "CENTER";
        msg = `Now placing the check ${next.guide === "CENTER" ? "in the center" : `against the ${next.guide.toLowerCase()} guide`}. Print the test again.`;
      } else if (outcome === "shrunk") { setStep("scale-bad"); return; }
      else if (outcome === "nothing") { msg = single ? "Check that the paper is in the manual feed and that the print dialog uses the manual-feed tray; then print again. If the printer asks for Letter paper, choose the check-sized page below." : "Check the printer is loaded and selected, then print again."; }
      else if (outcome === "ok") { setStep("done"); return; }
      if (JSON.stringify(next) !== JSON.stringify(st)) await save(next);
      setNote(msg);
      setStep("align");
    } catch (x) { setErr(x); }
  };
  return (
    <Modal title={`Printer setup assistant – ${fm?.label}`} onClose={onClose} wide>
      {show === "scale" && scalePdf ? <PdfViewer pdf={scalePdf} title="Scale check" onClose={() => setShow(null)} /> : null}
      {show === "test" && testPdf ? <PdfViewer pdf={testPdf} title="Alignment test" singleFeed={single} onClose={() => setShow(null)} /> : null}
      <ErrorBox error={err} />
      <p className="hint">These settings are yours only, for this check style and feed mode. They never change the Administrator's layout.</p>
      {step === "scale" || step === "scale-bad" ? (
        <>
          <h3>Step 1 – print scale</h3>
          <p>Print the scale check on plain paper and measure the line with a ruler.</p>
          <div className="row"><button onClick={printScale}>Print the scale check page</button></div>
          {step === "scale-bad" ? <div className="alert warn">The browser is changing the size. Fix the scale setting below and print the scale check again.</div> : null}
          <BrowserTips singleFeed={false} />
          <p><b>Is the line exactly 5 inches?</b></p>
          <div className="actions left"><button className="primary" onClick={() => setStep("align")}>Yes, exactly 5 inches</button><button onClick={() => setStep("scale-bad")}>No</button></div>
        </>
      ) : step === "align" ? (
        <>
          <h3>Step 2 – alignment test</h3>
          {note ? <div className="alert info" role="status">{note}</div> : null}
          <p>Print the test page {single ? "fed the same way as the check (cut plain paper to the check's size, or use a scrap check)" : "on plain paper in the same tray"} and hold it over a blank check against a light.</p>
          <p className="hint">Current settings: {adjText(st)}.</p>
          <div className="row"><button className="primary" onClick={printTest}>Make the test page</button></div>
        </>
      ) : step === "result" ? (
        <>
          <h3>Step 3 – what happened?</h3>
          <div className="row"><button className="link" onClick={() => setShow("test")}>Show the test page again</button></div>
          <fieldset className="choices">
            {[["ok", "It lines up with the check"], ["shifted", "Everything is shifted"], ["shrunk", "It printed smaller or larger"],
              ...(single ? [["wrongplace", "It printed on the wrong part of the paper"], ["papersize", "The printer showed a paper-size error"]] : []),
              ["nothing", "Nothing printed"]].map(([k, l]) => (
              <label key={k} className="check"><input type="radio" name="outcome" checked={outcome === k} onChange={() => setOutcome(k)} /> {l}</label>
            ))}
          </fieldset>
          {outcome === "shifted" ? (
            <div className="row">
              <Field label="The printing landed too far">
                <select value={dir} onChange={(e) => setDir(e.target.value)}>
                  <option value="down">down (toward the bank numbers)</option><option value="up">up (toward the top edge)</option>
                  <option value="right">right (toward the date end)</option><option value="left">left (toward the pay-to end)</option>
                </select>
              </Field>
              <Field label="By about"><select value={amt} onChange={(e) => setAmt(e.target.value)}>{STEPS.map((s) => <option key={s} value={s}>{s === 1 / 16 ? "1/16" : s === 1 / 8 ? "1/8" : s === 3 / 16 ? "3/16" : "1/4"} inch</option>)}</select></Field>
            </div>
          ) : null}
          <div className="actions left"><button className="primary" disabled={!outcome} onClick={apply}>Continue</button></div>
        </>
      ) : (
        <>
          <div className="alert success" role="status"><strong>Your printer is set up for this feed mode.</strong> Settings: {adjText(st)}.</div>
          <div className="actions"><button className="primary" onClick={onClose}>Close</button></div>
        </>
      )}
    </Modal>
  );
}

